Repository multinet-app/multinet, pull requests merged in 2020-02, with the labels that each got.

#290 Add logo
  client/src/assets/app_logo.png
  client/src/components/Sidebar.vue
Labels: ui

#310 Logo addition and recolor
  client/src/assets/Kitware_Logo.png
  client/src/assets/Ulogo_100px.png
  client/src/assets/kw_logo.png
  client/src/assets/nsf_logo.png
  client/src/assets/utah_logo.png
  client/src/assets/vdl_logo.png
  client/src/views/FrontPage.vue
Labels: design

#315 Convert fields with "filled" prop to "outlined"
  client/src/components/FileUploadForm.vue
  client/src/components/GraphCreateForm.vue
  client/src/components/WorkspaceDialog.vue
Labels: ui

#328 Add documentation links to about panel
  client/src/components/AExt.vue
  client/src/components/AboutDialog.vue
Labels: enhancement, ui
